name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build_job

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - name: Grant permission for execution
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Build and Push Docker Image
      uses: cloudposse/github-action-docker-build-push@main
      with:
        registry: docker.io
        repository: freemanoff/demo
        login: "${{ secrets.DOCKERHUB_USERNAME }}"
        password: "${{ secrets.DOCKERHUB_PASSWORD }}"
        platforms: linux/amd64,linux/arm64